import fs from 'node:fs';
import path from 'node:path';

import { ImportedModulesPrivateOptions } from './types.d';

/**
 * Sync version of the directory reader.
 *
 * !important this function will block the event loop until it finishes.
 * I use *for loop* instead of forEach because it is faster.
 * I define the *counter* variable outside the loop because it is faster. Because it is not redefined every iteration.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @param {string} targetDirectoryPath - The path to the directory to import modules from. Required for recursive calls.
 * @param {Set<string>} visitedDirectoryPaths - The real directory paths that were already scanned.
 * @returns {string[]} An array of file paths.
 */
export default function readDirectorySync(
  options: ImportedModulesPrivateOptions,
  targetDirectoryPath: string,
  visitedDirectoryPaths = new Set<string>(),
): string[] {
  const realTargetDirectoryPath = fs.realpathSync(targetDirectoryPath);

  if (visitedDirectoryPaths.has(realTargetDirectoryPath)) {
    return [];
  }

  visitedDirectoryPaths.add(realTargetDirectoryPath);

  const receivedItemsPaths = fs.readdirSync(targetDirectoryPath);
  const receivedDirectoriesPaths: string[] = [];
  const receivedFilesPaths: string[] = [];

  // Get the files and directories paths from the target directory.
  let itemsCounter = 0;
  for (itemsCounter; itemsCounter < receivedItemsPaths.length; itemsCounter += 1) {
    const itemPath = path.join(`${targetDirectoryPath}`, `${receivedItemsPaths[itemsCounter]}`);
    const stat = fs.statSync(itemPath);

    if (stat.isDirectory() && options.includeSubdirectories) {
      receivedDirectoriesPaths.push(itemPath);
    } else if (stat.isFile()) {
      receivedFilesPaths.push(itemPath);
    }
  }

  // Recursively get the files paths from the subdirectories.
  let directoriesCounter = 0;
  for (directoriesCounter; directoriesCounter < receivedDirectoriesPaths.length; directoriesCounter += 1) {
    const nestedDirectoryPath = receivedDirectoriesPaths[directoriesCounter] as string;
    const files = readDirectorySync(options, nestedDirectoryPath, visitedDirectoryPaths);

    receivedFilesPaths.push(...files);
  }

  // Return the files paths.
  return receivedFilesPaths;
}
