import { promises as fs } from 'node:fs';
import path from 'node:path';

import { ImportedModulesPrivateOptions } from './types.d';

/**
 * Async version of the directory reader.
 *
 * I use *for loop* instead of forEach because it is faster.
 * I define the *counter* variable outside the loop because it is faster. Because it is not redefined every iteration.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @param {string} targetDirectoryPath - The path to the directory to import modules from. Required for recursive calls.
 * @param {Set<string>} visitedDirectoryRealPaths - Tracks visited real paths to prevent symbolic link cycles.
 * @returns {Promise<string[]>} An object containing all imported modules.
 */
export default async function readDirectoryAsync(
  options: ImportedModulesPrivateOptions,
  targetDirectoryPath: string,
  visitedDirectoryRealPaths: Set<string> = new Set(),
): Promise<string[]> {
  const currentDirectoryRealPath = await fs.realpath(targetDirectoryPath);

  if (visitedDirectoryRealPaths.has(currentDirectoryRealPath)) {
    return [];
  }

  visitedDirectoryRealPaths.add(currentDirectoryRealPath);

  const receivedItemsPaths = await fs.readdir(targetDirectoryPath);

  const result = await Promise.all(
    receivedItemsPaths.map(async (itemPath) => {
      const receivedFilesPaths = [];

      const relativeItemPath = path.join(`${targetDirectoryPath}`, `${itemPath}`);

      const stat = await fs.stat(relativeItemPath);

      if (stat.isDirectory() && options.includeSubdirectories) {
        const files = await readDirectoryAsync(options, relativeItemPath, visitedDirectoryRealPaths);

        receivedFilesPaths.push(...files);
      } else if (stat.isFile()) {
        receivedFilesPaths.push(relativeItemPath);
      }

      return receivedFilesPaths;
    }),
  );

  return result.flat();
}
