import path from 'node:path';

import readDirectoryAsync from './directory-reader-async';
import readDirectorySync from './directory-reader-sync';
import { ImportedModules, ImportedModulesPrivateOptions } from './types.d';

const VALID_IMPORT_EXTENSIONS = new Set(['.js', '.mjs', '.ts', '.json']);

const handlers = { async: asyncHandler, sync: syncHandler };

/**
 * Check whether a file should be imported.
 * @param {string} filePath - The path to the file.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @returns {boolean} Whether the file is importable.
 */
function isImportableModule(filePath: string, options: ImportedModulesPrivateOptions): boolean {
  const { ext: fileExtension } = path.parse(filePath);
  const isValidModuleExtension = VALID_IMPORT_EXTENSIONS.has(fileExtension);
  const isDeclarationFile = filePath.endsWith('.d.ts');
  const isValidFilePath = options.importPattern ? options.importPattern.test(filePath) : true;

  return isValidModuleExtension && isValidFilePath && !isDeclarationFile;
}

/**
 * Check whether a file should be invalidated in require cache.
 * @param {string} filePath - The path to the file.
 * @returns {boolean} Whether the file cache can be invalidated.
 */
function isCacheInvalidationCandidate(filePath: string): boolean {
  const { ext: fileExtension } = path.parse(filePath);
  const isValidModuleExtension = VALID_IMPORT_EXTENSIONS.has(fileExtension);
  const isDeclarationFile = filePath.endsWith('.d.ts');

  return isValidModuleExtension && !isDeclarationFile;
}

/**
 * Filter input file paths and return only importable module paths.
 * @param {string[]} filesPaths - The list of file paths to filter.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @returns {string[]} The list of importable module paths.
 */
function getImportableModulePaths(
  filesPaths: string[],
  options: ImportedModulesPrivateOptions,
): string[] {
  return filesPaths.filter((filePath) => isImportableModule(filePath, options));
}

/**
 * Filter input file paths and return module paths to invalidate.
 * @param {string[]} filesPaths - The list of file paths to filter.
 * @returns {string[]} The list of module paths to invalidate in cache.
 */
function getCacheInvalidationModulePaths(filesPaths: string[]): string[] {
  return filesPaths.filter((filePath) => isCacheInvalidationCandidate(filePath));
}

/**
 * Remove imported modules from Node.js require cache.
 * @param {string[]} modulePaths - The module paths to invalidate.
 * @returns {void}
 */
function clearRequireCache(modulePaths: string[]): void {
  for (const modulePath of modulePaths) {
    // eslint-disable-next-line security/detect-non-literal-require, @typescript-eslint/no-var-requires, unicorn/prefer-module
    const resolvedModulePath = require.resolve(modulePath) as string;

    // eslint-disable-next-line security/detect-non-literal-require, @typescript-eslint/no-var-requires, unicorn/prefer-module
    delete require.cache[resolvedModulePath];
  }
}

/**
 * Synchronously import modules from the specified directory.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @returns {ImportedModules} An object containing all imported modules.
 */
function syncHandler(options: ImportedModulesPrivateOptions): ImportedModules {
  const modules = {};

  const filesPaths = readDirectorySync(options, options.targetDirectoryPath);
  const importableModulePaths = getImportableModulePaths(filesPaths, options);
  const cacheInvalidationModulePaths = getCacheInvalidationModulePaths(filesPaths);

  if (options.forceReload) {
    clearRequireCache(cacheInvalidationModulePaths);
  }

  let index = 0;

  for (const filePath of importableModulePaths) {
    importModule(filePath, index, options, modules);
    index += 1;
    if (index === options.limit) break;
  }

  return modules;
}

/**
 * Asynchronously import modules from the specified directory.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @returns {Promise<ImportedModules>} An object containing all imported modules.
 */
async function asyncHandler(options: ImportedModulesPrivateOptions): Promise<ImportedModules> {
  const modules = {};

  const filesPaths = await readDirectoryAsync(options, options.targetDirectoryPath);
  const importableModulePaths = getImportableModulePaths(filesPaths, options);
  const cacheInvalidationModulePaths = getCacheInvalidationModulePaths(filesPaths);

  if (options.forceReload) {
    clearRequireCache(cacheInvalidationModulePaths);
  }

  let index = 0;

  for (const filePath of importableModulePaths) {
    importModule(filePath, index, options, modules);
    index += 1;
    if (index === options.limit) break;
  }

  return modules;
}

/**
 * Import a module and add it to the modules object.
 * @param {string} filePath - The path to the file to import.
 * @param {number} index - The index of the module.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @param {ImportedModules} modules - The object containing all imported modules.
 * @returns {boolean} Whether the module was imported or not.
 */
function importModule(
  filePath: string,
  index: number,
  options: ImportedModulesPrivateOptions,
  modules: ImportedModules,
) {
  const { name: fileName } = path.parse(filePath);

  const relativeModulePath = filePath.slice(options.targetDirectoryPath.length);

  // eslint-disable-next-line security/detect-non-literal-require, @typescript-eslint/no-var-requires, unicorn/prefer-module
  const importedModule = require(filePath) as unknown;

  modules[relativeModulePath] = importedModule;

  if (options.callback) {
    options.callback(fileName, relativeModulePath, importedModule, index);
  }
}

/**
 * Import all modules from the specified directory synchronously or asynchronously.
 * @param {ImportedModulesPrivateOptions} options - The private options generated by the preparePrivateOptions function.
 * @returns {ImportedModules | Promise<ImportedModules>} An object containing all imported modules.
 */
export default function importModules(
  options: ImportedModulesPrivateOptions,
): ImportedModules | Promise<ImportedModules> {
  if (!handlers[options.importMode]) {
    throw new Error(`Expected sync or async import method, but got: ${options.importMode}`);
  }

  return handlers[options.importMode](options);
}
